### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by ibhavikmakwana** [ibhavikmakwana/Manch#15]
Improve README.md to get the new developer or contributer can get start with the app easily.

- [x] Add a screenshots in the README.md

**Comment by danger-ahead** [comment]
Hi! I can help with this one. Kindly provide with the details. Also consider assigning me. Thanks!

**Comment by ibhavikmakwana** [comment]
Hey @danger-ahead This issue will remain open as long as development is going on, we will improve it if there's any missing part to run the app successfully. As of now there's no work on this.

**Comment by ibhavikmakwana** [comment]
Closing this as there is no need for improving a readme
