### ISSUE TITLE
Implement Google Sign Up/Sign In Integration

### ISSUE THREAD

**Issue by ibhavikmakwana** [ibhavikmakwana/Manch#37]
## Description:

This feature request proposes integrating Google Sign Up/Sign In functionalities into our Flutter application. Currently, users rely on email-based registration and login, which can be inconvenient and require remembering passwords. Integrating Google Sign Up/Sign In offers several advantages specific to the Flutter ecosystem:

**Simplified user experience:**

* Users can seamlessly create accounts or sign in using their existing Google credentials, eliminating the need for separate registration and password management within the Flutter app.
* Reduces friction during onboarding, leading to higher user engagement.

## Implementation Details:

* Integrate the `google_sign_in` plugin for Flutter to handle Google Sign In functionalities.
* Handle data mapping between Google user information and our application's user model.

**Comment by Mittal-Sudhanshu** [comment]
Please assign me this issue

**Comment by ibhavikmakwana** [comment]
Done @Mittal-Sudhanshu Looking forward to your contribution.

**Comment by ibhavikmakwana** [comment]
Hey @Mittal-Sudhanshu, let's keep it all right here in the comments! Feel free to share your thoughts below.

**Comment by Mittal-Sudhanshu** [comment]
Hey @ibhavikmakwana some of the files are ignored by .gitignore and without it I can't actually run the app

**Comment by ibhavikmakwana** [comment]
@Mittal-Sudhanshu Which file exactly, I have checked .gitignore file it looked good to me.

**Comment by Mittal-Sudhanshu** [comment]
@ibhavikmakwana have a look at these files:
*.g.dart
*.reflectable.dart

**Comment by ibhavikmakwana** [comment]
To fix the issue, run the following command in your terminal: `dart run build_runner build`. This will generate the required files on your local system.

**Comment by Mittal-Sudhanshu** [comment]
ok, also I need the base URL to continue the process

**Comment by Mittal-Sudhanshu** [comment]
Just setup my keys will be reverting you with a PR soon
